export interface Place {
  id: string;
  name: string;
  kingdom: string;
  type: 'heritage' | 'museum' | 'umkm' | 'food';
  lat: number;
  lng: number;
  description: string;
  entryFee?: string;
  openHours?: string;
  specialty?: string[];
  whatToBuy?: string;
  imageUrl?: string;
}

export interface KingdomCentroid {
  name: string;
  lat: number;
  lng: number;
  period: string;
  description: string;
  color: string;
}

export const KINGDOM_CENTROIDS: KingdomCentroid[] = [
  { name: "Sriwijaya", lat: -3.0, lng: 104.7, period: "650–1377 CE", description: "The powerful maritime empire that controlled the spice trade routes.", color: "#D4A843" },
  { name: "Mataram Kuno", lat: -7.6, lng: 110.2, period: "717–1006 CE", description: "The era of great temple builders, creators of Borobudur and Prambanan.", color: "#2D5A3D" },
  { name: "Singhasari", lat: -7.9, lng: 112.6, period: "1222–1292 CE", description: "The East Javanese kingdom that paved the way for Majapahit's glory.", color: "#8B0000" },
  { name: "Majapahit", lat: -7.5, lng: 112.4, period: "1293–1527 CE", description: "The golden age of Nusantara, uniting the archipelago under one rule.", color: "#C4622D" },
  { name: "Demak", lat: -6.9, lng: 110.6, period: "1475–1554 CE", description: "The first major Islamic sultanate on Java, a center of faith and trade.", color: "#2E8B57" },
  { name: "Mataram Islam", lat: -7.8, lng: 110.4, period: "1587–1755 CE", description: "The successor of Mataram Kuno, shaping modern Javanese court culture.", color: "#4B3621" },
  { name: "Kediri", lat: -7.8, lng: 112.0, period: "1042–1222 CE", description: "A center of classical Javanese literature and refined arts.", color: "#704214" },
  { name: "Kahuripan", lat: -7.6, lng: 112.2, period: "1019–1045 CE", description: "The kingdom of Airlangga, known for its irrigation and wisdom.", color: "#556B2F" },
  { name: "Medang", lat: -7.5, lng: 112.0, period: "732–1006 CE", description: "The predecessor of the great East Javanese dynasties.", color: "#3D2B1F" },
  { name: "Pajang", lat: -7.5, lng: 110.7, period: "1568–1586 CE", description: "A brief but vital bridge between the era of Demak and Mataram Islam.", color: "#5C4033" },
];

export const MUSEUMS: Place[] = [
  { id: "m1", name: "Museum Nasional Jakarta", kingdom: "Nusantara", type: "museum", lat: -6.1763, lng: 106.8227, description: "The largest collection of Indonesian history and ethnography.", entryFee: "Rp 5.000", openHours: "Tue-Sun 08:00-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Museum_Nasional_Indonesia.jpg/640px-Museum_Nasional_Indonesia.jpg" },
  { id: "m2", name: "Museum Sonobudoyo Yogyakarta", kingdom: "Mataram Islam", type: "museum", lat: -7.8009, lng: 110.3650, description: "Javanese culture and heritage museum in the heart of Yogyakarta.", entryFee: "Rp 5.000", openHours: "Tue-Sun 08:00-15:30", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Museum_Sonobudoyo.jpg/640px-Museum_Sonobudoyo.jpg" },
  { id: "m3", name: "Museum Majapahit Trowulan", kingdom: "Majapahit", type: "museum", lat: -7.5519, lng: 112.3758, description: "Site museum at the ancient capital of the Majapahit Empire.", entryFee: "Rp 3.000", openHours: "Daily 07:30-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Trowulan_museum.jpg/640px-Trowulan_museum.jpg" },
  { id: "m4", name: "Museum Batik Pekalongan", kingdom: "Nusantara", type: "museum", lat: -6.8886, lng: 109.6753, description: "Dedicated to the coastal batik traditions of Northern Java.", entryFee: "Rp 10.000", openHours: "Tue-Sun 09:00-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Museum_Batik_Pekalongan.jpg/640px-Museum_Batik_Pekalongan.jpg" },
  { id: "m5", name: "Museum Wayang Jakarta", kingdom: "Nusantara", type: "museum", lat: -6.1352, lng: 106.8133, description: "Extensive collection of wayang puppets from across Indonesia.", entryFee: "Rp 5.000", openHours: "Tue-Sun 09:00-15:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Museum_Wayang_Jakarta.jpg/640px-Museum_Wayang_Jakarta.jpg" },
  { id: "m6", name: "Museum Tekstil Jakarta", kingdom: "Nusantara", type: "museum", lat: -6.1871, lng: 106.8138, description: "Discover the rich textile traditions of the archipelago.", entryFee: "Rp 5.000", openHours: "Tue-Sun 09:00-15:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Museum_Tekstil_Jakarta.jpg/640px-Museum_Tekstil_Jakarta.jpg" },
  { id: "m7", name: "Museum Keris Surakarta", kingdom: "Mataram Islam", type: "museum", lat: -7.5652, lng: 110.8188, description: "Dedicated to the art and history of the Indonesian kris.", entryFee: "Rp 5.000", openHours: "Tue-Sun 09:00-14:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Keris_collection.jpg/640px-Keris_collection.jpg" },
  { id: "m8", name: "Galeri Nasional Jakarta", kingdom: "Nusantara", type: "museum", lat: -6.1986, lng: 106.8322, description: "Home to Indonesia's finest modern and contemporary art.", entryFee: "Free", openHours: "Tue-Sun 10:00-18:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Galeri_Nasional_Indonesia.jpg/640px-Galeri_Nasional_Indonesia.jpg" },
  { id: "m9", name: "Museum Negeri Bali", kingdom: "Bali", type: "museum", lat: -8.6581, lng: 115.2134, description: "Showcasing Balinese art, culture, and prehistoric artifacts.", entryFee: "Rp 50.000", openHours: "Mon-Fri 08:00-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Bali_Museum.jpg/640px-Bali_Museum.jpg" },
  { id: "m10", name: "Museum Ullen Sentalu Yogyakarta", kingdom: "Mataram Islam", type: "museum", lat: -7.5963, lng: 110.4264, description: "Private museum of Javanese culture and Mataram royalty.", entryFee: "Rp 50.000", openHours: "Tue-Sun 08:30-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ullen_Sentalu_Museum.jpg/640px-Ullen_Sentalu_Museum.jpg" },
  { id: "m11", name: "Museum Brawijaya Malang", kingdom: "Singhasari", type: "museum", lat: -7.9831, lng: 112.6265, description: "Military history museum with a focus on East Javanese heritage.", entryFee: "Rp 5.000", openHours: "Daily 08:00-15:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Museum_Brawijaya_Malang.jpg/640px-Museum_Brawijaya_Malang.jpg" },
  { id: "m12", name: "Museum Provinsi Surabaya", kingdom: "Majapahit", type: "museum", lat: -7.2475, lng: 112.7378, description: "Historical museum showcasing East Java's rich cultural heritage.", entryFee: "Rp 5.000", openHours: "Tue-Sun 09:00-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Surabaya_Museum.jpg/640px-Surabaya_Museum.jpg" },
];

export const UMKM_ARTISANS: Place[] = [
  { id: "u1", name: "Kampung Batik Laweyan Solo", kingdom: "Mataram Islam", type: "umkm", lat: -7.5701, lng: 110.7883, description: "Historic batik district with grand merchant houses.", specialty: ["batik", "heritage district"], openHours: "Daily 08:00-18:00", whatToBuy: "Hand-drawn Batik", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Kampung_Batik_Laweyan.jpg/640px-Kampung_Batik_Laweyan.jpg" },
  { id: "u2", name: "Kotagede Silver District Yogyakarta", kingdom: "Mataram Islam", type: "umkm", lat: -7.8371, lng: 110.3949, description: "The silver center of Yogyakarta since the 16th century.", specialty: ["silver jewelry", "crafts"], openHours: "Daily 09:00-17:00", whatToBuy: "Filigree Silver", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Kotagede_silverwork.jpg/640px-Kotagede_silverwork.jpg" },
  { id: "u3", name: "Jepara Wood Carving Center", kingdom: "Majapahit", type: "umkm", lat: -6.5898, lng: 110.6729, description: "Famous worldwide for intricate wood carvings and furniture.", specialty: ["ukiran kayu", "furniture"], openHours: "Daily 08:00-17:00", whatToBuy: "Teak Carvings", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Jepara_wood_carving.jpg/640px-Jepara_wood_carving.jpg" },
  { id: "u4", name: "Sentra Batik Trusmi Cirebon", kingdom: "Cirebon", type: "umkm", lat: -6.7235, lng: 108.5100, description: "The home of the iconic Megamendung batik pattern.", specialty: ["batik Cirebon", "megamendung"], openHours: "Daily 08:00-20:00", whatToBuy: "Megamendung Batik", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Batik_Megamendung.jpg/640px-Batik_Megamendung.jpg" },
  { id: "u5", name: "Kamasan Wayang Village Klungkung Bali", kingdom: "Bali", type: "umkm", lat: -8.5396, lng: 115.4045, description: "The birthplace of classical Balinese painting.", specialty: ["wayang painting", "traditional art"], openHours: "Daily 08:00-16:00", whatToBuy: "Kamasan Paintings", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Wayang_Kulit.jpg/640px-Wayang_Kulit.jpg" },
  { id: "u6", name: "Celuk Silver Village Bali", kingdom: "Bali", type: "umkm", lat: -8.5579, lng: 115.2909, description: "Renowned for its generations of skilled gold and silver smiths.", specialty: ["silver", "gold jewelry"], openHours: "Daily 08:00-18:00", whatToBuy: "Balinese Silver", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Celuk_Bali_silver.jpg/640px-Celuk_Bali_silver.jpg" },
  { id: "u7", name: "Pasar Seni Ancol Jakarta", kingdom: "Nusantara", type: "umkm", lat: -6.1229, lng: 106.8479, description: "A hub for artists and traditional craftsmen in the capital.", specialty: ["mixed crafts", "ukiran", "batik"], openHours: "Daily 10:00-20:00", whatToBuy: "Local Artworks", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Pasar_Seni_Ancol.jpg/640px-Pasar_Seni_Ancol.jpg" },
  { id: "u8", name: "Kampung Batik Jetis Sidoarjo", kingdom: "Majapahit", type: "umkm", lat: -7.4561, lng: 112.7184, description: "Known for its vibrant and distinct coastal batik style.", specialty: ["batik Sidoarjo"], openHours: "Daily 08:00-17:00", whatToBuy: "Sidoarjo Batik", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Batik_parang.jpg/640px-Batik_parang.jpg" },
  { id: "u9", name: "Sentra Gerabah Kasongan Yogyakarta", kingdom: "Mataram Islam", type: "umkm", lat: -7.8703, lng: 110.3544, description: "Pottery village specializing in artistic clay creations.", specialty: ["pottery", "ceramic crafts"], openHours: "Daily 08:00-17:00", whatToBuy: "Terracotta Art", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Kasongan_pottery.jpg/640px-Kasongan_pottery.jpg" },
  { id: "u10", name: "Pusat Kerajinan Tenun Sukarara Lombok", kingdom: "Sasak", type: "umkm", lat: -8.6869, lng: 116.3083, description: "Witness the traditional weaving of Songket and Tenun.", specialty: ["tenun Lombok"], openHours: "Daily 08:00-17:00", whatToBuy: "Songket Textiles", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Sumba_ikat.jpg/640px-Sumba_ikat.jpg" },
  { id: "u11", name: "Kampung Keris Madura Sumenep", kingdom: "Majapahit", type: "umkm", lat: -7.0000, lng: 113.8667, description: "The most active keris-making community remaining today.", specialty: ["keris forging"], openHours: "Daily 08:00-16:00", whatToBuy: "Custom Keris", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Keris_Majapahit.jpg/640px-Keris_Majapahit.jpg" },
  { id: "u12", name: "Pusat Ukiran Mas Ubud Bali", kingdom: "Bali", type: "umkm", lat: -8.5069, lng: 115.2625, description: "The heart of high-quality Balinese wood carving.", specialty: ["gold ukiran", "traditional Bali crafts"], openHours: "Daily 08:00-18:00", whatToBuy: "Statue Carvings", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Ubud_wood_carving.jpg/640px-Ubud_wood_carving.jpg" },
];

export const HERITAGE_SITES: Place[] = [
  { id: "h1", name: "Candi Borobudur", kingdom: "Mataram Kuno", type: "heritage", lat: -7.6079, lng: 110.2038, description: "The world's largest Buddhist temple, a UNESCO World Heritage Site built in the 9th century.", entryFee: "Rp 50.000", openHours: "Daily 06:30-16:30", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Borobudur-Nothwest-view.jpg/640px-Borobudur-Nothwest-view.jpg" },
  { id: "h2", name: "Candi Prambanan", kingdom: "Mataram Kuno", type: "heritage", lat: -7.7520, lng: 110.4915, description: "Magnificent 9th-century Hindu temple complex dedicated to the Trimurti.", entryFee: "Rp 50.000", openHours: "Daily 06:30-17:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Prambanan_temple_view.jpg/640px-Prambanan_temple_view.jpg" },
  { id: "h3", name: "Trowulan Archaeological Site", kingdom: "Majapahit", type: "heritage", lat: -7.5592, lng: 112.3811, description: "Ruins of the capital city of Majapahit, spread over 100 sq km.", entryFee: "Rp 5.000", openHours: "Daily 07:00-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Trowulan_museum.jpg/640px-Trowulan_museum.jpg" },
  { id: "h4", name: "Candi Singhasari", kingdom: "Singhasari", type: "heritage", lat: -7.8863, lng: 112.6644, description: "13th-century Hindu-Buddhist temple built in honor of King Kertanegara.", entryFee: "Rp 5.000", openHours: "Daily 07:30-16:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Singosari_temple.jpg/640px-Singosari_temple.jpg" },
  { id: "h5", name: "Muara Jambi", kingdom: "Sriwijaya", type: "heritage", lat: -1.4727, lng: 103.6583, description: "One of the largest and best-preserved Buddhist temple complexes in Southeast Asia.", entryFee: "Rp 5.000", openHours: "Daily 08:00-17:00", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Muara_Jambi_temple.jpg/640px-Muara_Jambi_temple.jpg" },
];

export const FOOD_STANDS: Place[] = [
  { id: "f1", name: "Pasar Beringharjo Yogyakarta", kingdom: "Mataram Islam", type: "food", lat: -7.7975, lng: 110.3650, description: "Yogyakarta's most iconic traditional market, operating since the 18th century alongside the Keraton palace.", specialty: ["Gudeg", "Bakpia", "Kipo", "Jenang"], openHours: "Daily 08:00-21:00", whatToBuy: "Gudeg & Batik snacks", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Pasar_Beringharjo.jpg/640px-Pasar_Beringharjo.jpg" },
  { id: "f2", name: "Kawasan Kuliner Ikan Bakar Jimbaran", kingdom: "Bali", type: "food", lat: -8.7847, lng: 115.1609, description: "World-famous Jimbaran beach seafood grills on the sand — fresh fish caught daily and grilled over coconut husk.", specialty: ["Ikan Bakar", "Udang Bakar", "Jukut Urap", "Babi Guling nearby"], openHours: "Daily 11:00-22:00", whatToBuy: "Fresh grilled seafood", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Jimbaran_beach_restaurant.jpg/640px-Jimbaran_beach_restaurant.jpg" },
  { id: "f3", name: "Kawasan Kuliner Sate Madura Surabaya", kingdom: "Majapahit", type: "food", lat: -7.2575, lng: 112.7521, description: "The epicenter of Sate Madura in East Java — charcoal-grilled skewers with black peanut sauce.", specialty: ["Sate Kambing", "Sate Ayam", "Lontong", "Soto Madura"], openHours: "Daily 09:00-22:00", whatToBuy: "Sate Madura platter", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Sate_Madura.jpg/640px-Sate_Madura.jpg" },
  { id: "f4", name: "Pasar Bawah Bukittinggi", kingdom: "Minangkabau", type: "food", lat: -0.3033, lng: 100.3682, description: "Bukittinggi's vibrant lower market where authentic Padang food ingredients and ready-to-eat dishes are found.", specialty: ["Rendang", "Dendeng Balado", "Gulai", "Soto Padang"], openHours: "Daily 06:00-18:00", whatToBuy: "Rendang & Dadiah", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Pasar_Bawah_Bukittinggi.jpg/640px-Pasar_Bawah_Bukittinggi.jpg" },
  { id: "f5", name: "Kampung Melayu Street Food Jambi", kingdom: "Sriwijaya", type: "food", lat: -1.5975, lng: 103.6300, description: "Traditional Melayu food streets in Jambi featuring ancient Sriwijayan culinary heritage.", specialty: ["Tempoyak", "Pempek Jambi", "Gulai Ikan Patin", "Mie Celor"], openHours: "Daily 10:00-23:00", whatToBuy: "Tempoyak & Pempek", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Jambi_traditional_food.jpg/640px-Jambi_traditional_food.jpg" },
  { id: "f6", name: "Jalan Pandanaran Semarang Kuliner", kingdom: "Demak", type: "food", lat: -6.9910, lng: 110.4120, description: "Semarang's famous food street where Lumpia (spring rolls), Wingko, and Tahu Gimbal are sold by generations of vendors.", specialty: ["Lumpia Semarang", "Wingko Babat", "Tahu Gimbal", "Mie Kopyok"], openHours: "Daily 09:00-22:00", whatToBuy: "Lumpia & Wingko", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Lumpia_Semarang.jpg/640px-Lumpia_Semarang.jpg" },
  { id: "f7", name: "Pasar Badung Bali", kingdom: "Bali", type: "food", lat: -8.6578, lng: 115.2179, description: "Bali's largest traditional market with fresh produce, spices, and traditional Balinese food stalls.", specialty: ["Nasi Campur Bali", "Babi Guling", "Jukut Urap", "Tipat Cantok"], openHours: "Daily 04:00-18:00", whatToBuy: "Balinese spice mixes", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Pasar_Badung_Bali.jpg/640px-Pasar_Badung_Bali.jpg" },
  { id: "f8", name: "Kawasan Rawon Nguling Pasuruan", kingdom: "Majapahit", type: "food", lat: -7.6458, lng: 112.9013, description: "The birthplace of Rawon, East Java's iconic black beef soup made with keluak nut — a dish dating to the Majapahit era.", specialty: ["Rawon", "Nasi Rawon", "Sate Klopo", "Tahu Campur"], openHours: "Daily 06:00-20:00", whatToBuy: "Rawon soto", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Rawon_soup.jpg/640px-Rawon_soup.jpg" },
  { id: "f9", name: "Pasar Tradisional Tomohon Sulawesi", kingdom: "Minahasa", type: "food", lat: 1.3325, lng: 124.8360, description: "The famous Minahasa market known for exotic and traditional North Sulawesi ingredients and prepared dishes.", specialty: ["Tinutuan", "Ayam Rica-Rica", "Pisang Goreng", "Cakalang Fufu"], openHours: "Daily 05:00-15:00", whatToBuy: "Cakalang Fufu & Rica-Rica", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Tomohon_market.jpg/640px-Tomohon_market.jpg" },
  { id: "f10", name: "Pusat Kuliner Soto Lamongan", kingdom: "Majapahit", type: "food", lat: -7.1173, lng: 112.4150, description: "Home of Soto Lamongan, arguably Indonesia's most beloved chicken soup — sold from portable stalls to grand restaurants.", specialty: ["Soto Lamongan", "Nasi Boran", "Lele Goreng", "Krupuk Rambak"], openHours: "Daily 06:00-22:00", whatToBuy: "Soto Lamongan set", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Soto_Lamongan.jpg/640px-Soto_Lamongan.jpg" },
  { id: "f11", name: "Pasar Lama Tangerang", kingdom: "Nusantara", type: "food", lat: -6.1783, lng: 106.6367, description: "Historic Chinese-Betawi fusion food market operating for 300+ years near the Cisadane river.", specialty: ["Laksa Tangerang", "Nasi Uduk", "Otak-otak", "Roti Gambang"], openHours: "Daily 06:00-15:00", whatToBuy: "Laksa & Kue Apem", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Pasar_Lama_Tangerang.jpg/640px-Pasar_Lama_Tangerang.jpg" },
  { id: "f12", name: "Kawasan Kuliner Nasi Padang Padang", kingdom: "Minangkabau", type: "food", lat: -0.9471, lng: 100.4172, description: "The city of origin for Nasi Padang — over 300 restaurants serving authentic Minangkabau cuisine with 20+ dishes.", specialty: ["Rendang Sapi", "Gulai Otak", "Ayam Pop", "Sambal Ijo", "Dendeng Batokok"], openHours: "Daily 07:00-22:00", whatToBuy: "Rendang & Keripik Balado", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Nasi_Padang.jpg/640px-Nasi_Padang.jpg" },
];
